# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-25 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180916_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
    ]
